name: snapshot

on:
  pull_request:
    branches:
      - "snapshot/**"

# on:
#   push:
#     branches: ["main"]
#     paths-ignore:
#       - README.md
#       - .gitignore
#   pull_request:
#     branches: ["*"]
#     paths-ignore:
#       - README.md
#       - .gitignore

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    timeout-minutes: 30
    strategy:
      fail-fast: true

    name: forge snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge snapshot
        # make fuzzing deterministic to keep snapshots consistent
        run: |
          forge snapshot --check --fuzz-seed 42
        id: snapshot
